#!/bin/bash

[ "`whoami`" = root ] || exec sudo "$0" "$@"

DOWNLOADARGS='-c -s16 -k1M -x16'
DNS=""

if ping -c 1 -W 1 180.76.76.76 2>/dev/null | grep -q -i "ttl"; then
  DNS="--async-dns-server=180.76.76.76"
fi

if ping -c 1 -W 2 8.8.8.8 2>/dev/null | grep -q -i "ttl"; then
  DNS="--async-dns-server=8.8.8.8"
fi

if echo "$@" | grep -q "upgrade\|install\|dist-upgrade\|full-upgrade\|build-dep"; then
  APT=$([ $(command -v apt) ] && echo "apt" || echo "apt-get")
  cd /var/cache/apt/archives/

  # Download unfinished jobs
  [ $(command -v aria2c) ] || $APT install -y aria2
  [[ -f /var/cache/apt/archives/apt-fast.list ]] && aria2c $DOWNLOADARGS $DNS -i apt-fast.list

  # Create new jobs
  $APT -y --print-uris $@ | grep -E -o -e "(ht|f)tp[s]?://[^\']+" | tee apt-fast.list && aria2c -c $DOWNLOADARGS $DNS -i apt-fast.list

  echo $APT $@
  $APT $@ && rm -f /var/cache/apt/archives/apt-fast.list
elif echo "$@" | grep -q "update"; then
  APT=$([ $(command -v apt) ] && echo "apt" || echo "apt-get")
  $APT -o 'Acquire::Queue-mode=access; APT::Acquire=Retries 3;' update

elif echo "$@" | grep -q "\-S"; then
  cd /var/cache/pacman/pkg/

  # Download unfinished jobs
  [ $(command -v aria2c) ] || pacman -S --noconfirm --needed aria2
  [[ -f /var/cache/pacman/pkg/apt-fast.list ]] && aria2c $DOWNLOADARGS $DNS -i apt-fast.list

  # Create new jobs
  pacman -Syup | grep -E -o -e "(ht|f)tp[s]?://[^\']+" | tee apt-fast.list && aria2c -c $DOWNLOADARGS $DNS -i apt-fast.list
  pacman -Sup $(echo " $@" | sed "s/ -[a-zA-Z-]\+//g") | grep -E -o -e "(ht|f)tp[s]?://[^\']+" | tee apt-fast.list && aria2c -c $DOWNLOADARGS $DNS -i apt-fast.list

  echo "pacman $@"
  pacman $@ && rm -f /var/cache/pacman/pkg/apt-fast.list
fi
