#!/bin/bash

while true; do
  sleep 20s
  if ! ping -c 1 8.8.8.8 | grep -q -i "ttl"; then
    systemctl restart NetworkManager.service
    systemctl restart networking.service
    systemctl restart teamviewerd.service
    echo $(date +"%m/%d/%Y %I:%M:%p") >> /home/Reconnect.log
    if [ $(cat /home/Reconnect.log | wc -l) -gt 20 ]; then
      sed -i '1d' /home/Reconnect.log
    fi
  fi

  if [[ $(command -v teamviewer) ]]; then
    systemctl is-active teamviewerd.service >/dev/null 2>&1
    if [[ $? != 0 ]]; then # if exit code is not zero, restart
      systemctl restart teamviewerd.service
      echo $(date +"%m/%d/%Y %I:%M:%p") "teamviewer" >> /home/Reconnect.log
      if [ $(cat /home/Reconnect.log | wc -l) -gt 20 ]; then
        sed -i '1d' /home/Reconnect.log
      fi
    fi
  fi
done
